// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {desktop} from '../models';
import {memory} from '../models';
import {presets} from '../models';

export function Agents():Promise<Array<app.AgentCard>>;

export function Chat(arg1:string,arg2:string):Promise<app.ChatDetail>;

export function ChatSend(arg1:desktop.ChatSendRequest):Promise<app.ChatDetail>;

export function ChatStart(arg1:desktop.ChatStartRequest):Promise<app.ChatDetail>;

export function Chats(arg1:string,arg2:number):Promise<Array<app.ChatSummary>>;

export function ChooseWorkspaceDirectory(arg1:string):Promise<string>;

export function DesktopLogPath():Promise<string>;

export function Home(arg1:string):Promise<app.HomeSnapshot>;

export function InitWorkspace(arg1:desktop.WorkspaceInitRequest):Promise<app.WorkspaceSummary>;

export function LiveApps(arg1:string,arg2:string):Promise<Array<app.LiveAppSummary>>;

export function LogFrontend(arg1:string,arg2:string):Promise<void>;

export function Memory(arg1:string):Promise<memory.Summary>;

export function Preset(arg1:string):Promise<app.PresetPreview>;

export function PresetInstall(arg1:desktop.PresetInstallRequest):Promise<presets.InstallResult>;

export function PresetInstallPreview(arg1:string,arg2:string):Promise<presets.InstallPreview>;

export function PresetRollback(arg1:desktop.PresetRollbackRequest):Promise<app.InstalledPresetSummary>;

export function Presets():Promise<Array<app.PresetCard>>;

export function ProjectState(arg1:string):Promise<app.ProjectState>;

export function Providers():Promise<Array<app.ProviderHealth>>;

export function Run(arg1:string,arg2:string):Promise<app.RunDetail>;

export function Runs(arg1:string,arg2:number):Promise<Array<app.RunSummary>>;

export function SaveWorkspaceFile(arg1:desktop.WorkspaceFileSaveRequest):Promise<app.WorkspaceFileDetail>;

export function Session(arg1:string,arg2:string):Promise<app.SessionDetail>;

export function Sessions(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string):Promise<Array<app.SessionSummary>>;

export function StartLessonDemo(arg1:desktop.LiveAppStartRequest):Promise<app.LiveAppDetail>;

export function StartMaterialLiveApp(arg1:desktop.LiveAppStartRequest):Promise<app.LiveAppDetail>;

export function StopLiveApp(arg1:desktop.LiveAppStopRequest):Promise<app.LiveAppDetail>;

export function TaskPlan(arg1:desktop.TaskPlanRequest):Promise<app.RunSummary>;

export function TaskReview(arg1:desktop.TaskReviewRequest):Promise<app.RunDetail>;

export function TaskRun(arg1:desktop.TaskRunRequest):Promise<app.RunSummary>;

export function Workspace(arg1:string):Promise<app.WorkspaceSummary>;

export function WorkspaceFile(arg1:string,arg2:string):Promise<app.WorkspaceFileDetail>;

export function WorkspaceFiles(arg1:string,arg2:number):Promise<app.WorkspaceExplorer>;
