// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Agents() {
  return window['go']['wailsapp']['App']['Agents']();
}

export function Chat(arg1, arg2) {
  return window['go']['wailsapp']['App']['Chat'](arg1, arg2);
}

export function ChatSend(arg1) {
  return window['go']['wailsapp']['App']['ChatSend'](arg1);
}

export function ChatStart(arg1) {
  return window['go']['wailsapp']['App']['ChatStart'](arg1);
}

export function Chats(arg1, arg2) {
  return window['go']['wailsapp']['App']['Chats'](arg1, arg2);
}

export function ChooseWorkspaceDirectory(arg1) {
  return window['go']['wailsapp']['App']['ChooseWorkspaceDirectory'](arg1);
}

export function DesktopLogPath() {
  return window['go']['wailsapp']['App']['DesktopLogPath']();
}

export function EnsureLiveApp(arg1) {
  return window['go']['wailsapp']['App']['EnsureLiveApp'](arg1);
}

export function Home(arg1) {
  return window['go']['wailsapp']['App']['Home'](arg1);
}

export function InitWorkspace(arg1) {
  return window['go']['wailsapp']['App']['InitWorkspace'](arg1);
}

export function LiveApps(arg1, arg2) {
  return window['go']['wailsapp']['App']['LiveApps'](arg1, arg2);
}

export function LogFrontend(arg1, arg2) {
  return window['go']['wailsapp']['App']['LogFrontend'](arg1, arg2);
}

export function Memory(arg1) {
  return window['go']['wailsapp']['App']['Memory'](arg1);
}

export function OpenExternalURL(arg1) {
  return window['go']['wailsapp']['App']['OpenExternalURL'](arg1);
}

export function Preset(arg1) {
  return window['go']['wailsapp']['App']['Preset'](arg1);
}

export function PresetInstall(arg1) {
  return window['go']['wailsapp']['App']['PresetInstall'](arg1);
}

export function PresetInstallPreview(arg1, arg2) {
  return window['go']['wailsapp']['App']['PresetInstallPreview'](arg1, arg2);
}

export function PresetRollback(arg1) {
  return window['go']['wailsapp']['App']['PresetRollback'](arg1);
}

export function Presets() {
  return window['go']['wailsapp']['App']['Presets']();
}

export function ProjectState(arg1) {
  return window['go']['wailsapp']['App']['ProjectState'](arg1);
}

export function Providers() {
  return window['go']['wailsapp']['App']['Providers']();
}

export function Run(arg1, arg2) {
  return window['go']['wailsapp']['App']['Run'](arg1, arg2);
}

export function Runs(arg1, arg2) {
  return window['go']['wailsapp']['App']['Runs'](arg1, arg2);
}

export function SaveWorkspaceFile(arg1) {
  return window['go']['wailsapp']['App']['SaveWorkspaceFile'](arg1);
}

export function Session(arg1, arg2) {
  return window['go']['wailsapp']['App']['Session'](arg1, arg2);
}

export function Sessions(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['wailsapp']['App']['Sessions'](arg1, arg2, arg3, arg4, arg5);
}

export function StartLessonDemo(arg1) {
  return window['go']['wailsapp']['App']['StartLessonDemo'](arg1);
}

export function StartMaterialLiveApp(arg1) {
  return window['go']['wailsapp']['App']['StartMaterialLiveApp'](arg1);
}

export function StopLiveApp(arg1) {
  return window['go']['wailsapp']['App']['StopLiveApp'](arg1);
}

export function TaskPlan(arg1) {
  return window['go']['wailsapp']['App']['TaskPlan'](arg1);
}

export function TaskReview(arg1) {
  return window['go']['wailsapp']['App']['TaskReview'](arg1);
}

export function TaskRun(arg1) {
  return window['go']['wailsapp']['App']['TaskRun'](arg1);
}

export function Workspace(arg1) {
  return window['go']['wailsapp']['App']['Workspace'](arg1);
}

export function WorkspaceFile(arg1, arg2) {
  return window['go']['wailsapp']['App']['WorkspaceFile'](arg1, arg2);
}

export function WorkspaceFiles(arg1, arg2) {
  return window['go']['wailsapp']['App']['WorkspaceFiles'](arg1, arg2);
}
